--- #installing multiple pkgs
- name: loops playbook 
  hosts: webservers
  become: yes
  user: ansible
  connection: ssh

  tasks:
    - name: install packages
      yum:
        name: ['git', 'which','docker','mysql','tree','wget','httpd','java']
        state: installed
