--- #My conditional playbook
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: Install apache for debian fmaily
      command: apt-get install apache2 -y
      when: ansible_os_family == "Debian"

    - name: Install apache for redhat family
      command: yum install httpd -y
      when: ansible_os_family == "RedHat"

